<div data-bind="scope: 'favMusic'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "favMusic": {
                            "template": "Advox_FavMusicList/fav-music",
                            "component": "Advox_FavMusicList/js/fav-music"
                        }
                    }
                }
            }
    }
</script>